[package]
name = "rinf"
version = "7.3.0"
edition = "2021"
license = "MIT"
description = "Rust for native business logic, Flutter for flexible and beautiful GUI"
repository = "https://github.com/cunarist/rinf"
documentation = "https://rinf.cunarist.com"
rust-version = "1.80"

[features]
show-backtrace = ["backtrace"]
bevy = ["bevy_ecs"]

[dependencies]
rinf_command = { version = "7.3.0" }
rinf_proc = { version = "7.3.0" }
bevy_ecs = { version = "0.15", optional = true }

[target.'cfg(not(target_family = "wasm"))'.dependencies]
allo-isolate = "0.1.26"
os-thread-local = "0.1.3"
backtrace = { version = "0.3.69", optional = true }

[target.'cfg(target_family = "wasm")'.dependencies]
js-sys = "0.3.70"
wasm-bindgen = "0.2.95"
wasm-bindgen-futures = "0.4.45"

[lints.clippy]
unwrap_used = "deny"
expect_used = "deny"
